### ISSUE TITLE
Improve Album Search

### ISSUE THREAD

**Issue by danield2255** [danield2255/MusicArtistArchetypes#1]
- Be able to get albums from valid artists effectively from Spotify API, must be able to get deluxe album where there is one and must exclude live albums (might be worth just excluding the word 'live') 
- Get the proportion of songs that made the Hot 100 / total songs on the album
- Get Spotify metrics of all of these songs

**Comment by kbodwin** [comment]
Num of Hot 100 songs & length of album

Do we want to aggregate Spotify metrics into album-level measure?  How?
