### ISSUE TITLE
Clustering Album Behavior 

### ISSUE THREAD

**Issue by danield2255** [danield2255/MusicArtistArchetypes#2]
Cluster the behavior of each album of an artist, and this will be used ultimately to help cluster artists.
Mini - Roadmap of this:
1. Assemble data and create metrics 
   - Proportion of hot 100 songs on the album
   - Metrics of songs aggregated to album
2. Model creation - Unsupervised
   - Consider what kind of clustering algorithm to use 
   - Run a sort of parameter optimization 
       - Concurrently do some variable selection 
3. Find distances 
   - Consider the distances between album clusters. This can serve as a metric of similarity and differences.
   - Maybe that means that there are archetypes of albums?
   - Consider the value counts of albums in clusters by artists 
      - Maybe this also speaks to artist similarities/differences

Choices:
- The model: What will encapsulate the complexities of the data the best? 
- Variables: consider a dimension reduction 
- could choose to standardize popularity across all albums so that albums with no songs on Hot 100, or could choose to not include albums with no songs on the Hot 100. I personally think that really to understand an artist by their albums, we need to include them all

**Comment by kbodwin** [comment]
Aggregating song popularities for an album:
- Max Pop song
- Mean vs quartiles
- other?
