### ISSUE TITLE
Research Answers

### ISSUE THREAD

**Issue by kbodwin** [danield2255/MusicArtistArchetypes#5]
Example conclusion statements for:

* Clustering Billboard 100 songs based on popularity, complexity, and Spotify API data
* Clustering Albums based on only aggregated song data, then looking at Awards and/or Artists after
* Clustering Albums based on ALL data

**Comment by danield2255** [comment]
1. Songs in the top 10 of the billboard hot 100 are very similar to each other.

2. Ed Sheeran's albums with at least one song on Billboard Hot 100 are very similar to one another. 

3. Taylor Swift's first 2 albums are significantly different from her later albums.

4. (FOR POTENTIAL ARTIST CLUSTERING) Nickelback and 3 Doors Down are statistically very similar bands.
